### ISSUE TITLE
Thank You!

### ISSUE THREAD

**Issue by xeruf** [Colonial-Dev/vcard-qr#1]
Was looking for exactly this to make QR Codes for my business cards :)

Some notes from first use:
- default output name should be suffixed, for example by the name
- separation first/middle/last name?
- notes seem to only include a single line, which should either be clarified or fixed to allow multiline

**Comment by Colonial-Dev** [comment]
Glad you found my little weekend project useful :D

I just saw your PR come through when I was writing this - thank you!

As for the other points:
* Yeah, good idea. Could be useful if you want to make a lot in sequence.
* Definitely possible using the `N` (instead of `FN`) field!

**Comment by Colonial-Dev** [comment]
Just pushed support for both (`-p` switch for the former, optional prompt for the latter)!
