### ISSUE TITLE
Provide compiled binaries as releases

### ISSUE THREAD

**Issue by xplosionmind** [Colonial-Dev/vcard-qr#5]
I would love to use this nifty tool, but unfortunately I don’t have cargo installed, and I would prefer not to use it just for this little script.

Thanks a lot!

**Comment by Colonial-Dev** [comment]
Can do! Just give me a little while to set up the CI for it.

**Comment by xplosionmind** [comment]
Wow, thanks a lot!

**Comment by Colonial-Dev** [comment]
[Here](https://github.com/Colonial-Dev/vcard-qr/releases) you go! Let me know if you have any issues - I can't test all of these binaries myself, but they *should* work due to being compiled on native action runners.
